export default {
  'ui/slider': 'src/components/UI/Slider/index.js',
  'ui/table': 'src/components/UI/Table/index.js',
  'ui/tabs': 'src/components/UI/Tabs/index.js',
  'ui/calendar': 'src/components/UI/Calendar/index.js',
  'ui/accordion': 'src/components/UI/Accordion/index.js',
  'ui/icon': 'src/components/UI/Icon/index.js',
  'ui/button': 'src/components/UI/Button/index.js',
  'ui/pagination': 'src/components/UI/Pagination/index.js',
  'ui/odometer': 'src/components/UI/Odometer/index.js',
  'ui/loader': 'src/components/UI/Loader/index.js',
  
  'input/date': 'src/components/inputs/Date/index.js',
  'input/file': 'src/components/inputs/File/index.js',
  'input/dropdown': 'src/components/inputs/Dropdown/index.js',
  'input/search': 'src/components/inputs/Search/index.js',
  'input/rangeSlider': 'src/components/inputs/RangeSlider/index.js',
  'input/time': 'src/components/inputs/Time/index.js',
  'input/checkbox': 'src/components/inputs/Checkbox/index.js',
  'input/chips': 'src/components/inputs/Chips/index.js',
  'input/text': 'src/components/inputs/Text/index.js',
  'input/radio': 'src/components/inputs/Radio/index.js',
  'input/tab': 'src/components/inputs/Tab/index.js',
  'input/numberCounter': 'src/components/inputs/NumberCounter/index.js',
  'input/toggle': 'src/components/inputs/Toggle/index.js',
  'input/popup': 'src/components/inputs/Popup/index.js',

  'overlays/contextMenu': 'src/components/overlays/ContextMenu/index.js',
  'overlays/drawer': 'src/components/overlays/Drawer/index.js',
  'overlays/modal': 'src/components/overlays/Modal/index.js',
  
  'hooks/useActivify': 'src/hooks/useActivify/index.js',
  'hooks/useLoader': 'src/hooks/useLoader/index.js',
};
