export default {
  'ui/slider': 'src/components/UI/Slider/index.js',
  'ui/table': 'src/components/UI/Table/index.js',
  'ui/tabs': 'src/components/UI/Tabs/index.js',
  'ui/calendar': 'src/components/UI/Calendar/index.js',
  'ui/accordion': 'src/components/UI/Accordion/index.js',
  'ui/icon': 'src/components/UI/Icon/index.js',
  'ui/button': 'src/components/UI/Button/index.js',
  'ui/pagination': 'src/components/UI/Pagination/index.js',
  'ui/odometer': 'src/components/UI/Odometer/index.js',
  'ui/loader': 'src/components/UI/Loader/index.js',
  'ui/label': 'src/components/Inputs/_common/Label.js',
  
  'input/date': 'src/components/Inputs/Date/index.js',
  'input/file': 'src/components/Inputs/File/index.js',
  'input/dropdown': 'src/components/Inputs/Dropdown/index.js',
  'input/search': 'src/components/Inputs/Search/index.js',
  'input/rangeSlider': 'src/components/Inputs/RangeSlider/index.js',
  'input/time': 'src/components/Inputs/Time/index.js',
  'input/checkbox': 'src/components/Inputs/Checkbox/index.js',
  'input/chips': 'src/components/Inputs/Chips/index.js',
  'input/text': 'src/components/Inputs/Text/index.js',
  'input/radio': 'src/components/Inputs/Radio/index.js',
  'input/tab': 'src/components/Inputs/Tab/index.js',
  'input/numberCounter': 'src/components/Inputs/NumberCounter/index.js',
  'input/toggle': 'src/components/Inputs/Toggle/index.js',
  
  'overlays/contextMenu': 'src/components/Overlays/ContextMenu/index.js',
  'overlays/drawer': 'src/components/Overlays/Drawer/index.js',
  'overlays/modal': 'src/components/Overlays/Modal/index.js',
  'overlays/toast': 'src/components/Overlays/Toast/index.js',
  'overlays/tooltip': 'src/components/Overlays/Tooltip/index.js',

  'hooks/useActivify': 'src/hooks/useActivify/index.js',
  'hooks/useLoader': 'src/hooks/useLoader/index.js',
  
  'decorators/loader': 'src/decorators/Loader/index.js',
  'decorators/confirmationDialog': 'src/decorators/ConfirmationDialog/index.js',
  'decorators/toastMessage': 'src/decorators/ToastMessage/index.js',
  'decorators/activify': 'src/decorators/Activify/index.js',

  'theme/provider': 'src/components/Context/Provider.js',
};
