export { default as Slider} from './UI/Slider'
export { default as Table} from './UI/Table'
export { default as Tabs} from './UI/Tabs'
export { default as Calendar} from './UI/Calendar'
export { default as Accordion} from './UI/Accordion'
export { default as Icon} from './UI/Icon'
export { default as Button} from './UI/Button'
export { default as Pagination} from './UI/Pagination'
export { default as Odometer} from './UI/Odometer'
export { default as Loader} from './UI/Loader'
export { default as Input} from './inputs'

export { default as ContextMenu} from './overlays/ContextMenu'
export { default as Drawer} from './overlays/Drawer'
export { default as Modal} from './overlays/Modal'
